公司规模：{{cpscale}}
公司性质：{{cptype}}
公司行业：{{cptrade}}
工作经验：{{wkxp}}
工作性质：{{wkform}}
最低学历：{{degreerq}}
管理经验：{{x1}}
职位月薪：{{salary}}
招聘人数：{{rcnos}}
工作地点：{{wkplace}}
职位类别：{{x2}}
发布日期：{{data}}
职位描述{{jbdesc}}
公司介绍{{cpinfo}}